import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // `next-env.d.ts` is generated by Next and always uses triple-slash refs.
    ignores: ['.next/**', 'node_modules/**', 'public/sw.js', 'out/**', 'next-env.d.ts'],
  },
  {
    rules: {
      // R3F relies heavily on three.js prop mutation and untyped JSX intrinsics.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'react-hooks/exhaustive-deps': 'warn',
      'react/no-unknown-property': 'off',
    },
  },
];

export default eslintConfig;
