/**
 * UI primitives — the small set of controls the menus are built from.
 *
 * Written directly against Radix rather than generated by the shadcn CLI (which
 * is interactive and would need to be re-run by anyone cloning the repo). The
 * result is the same: unstyled, accessible Radix behaviour plus our own
 * Tailwind styling.
 *
 * Radix is doing real work here — focus trapping in dialogs, roving tabindex in
 * tab lists, correct ARIA on every control, keyboard interaction for sliders
 * and switches. All of that is required for the accessibility pass and none of
 * it is worth reimplementing.
 *
 * @module components/ui/primitives
 */

'use client';

import * as React from 'react';
import * as SliderPrimitive from '@radix-ui/react-slider';
import * as SwitchPrimitive from '@radix-ui/react-switch';
import * as TabsPrimitive from '@radix-ui/react-tabs';
import * as SelectPrimitive from '@radix-ui/react-select';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
import * as SeparatorPrimitive from '@radix-ui/react-separator';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { Check, ChevronDown } from 'lucide-react';

import { cn } from '@/lib/utils/cn';
import { getSynthEngine } from '@/components/audio/SynthEngine';
import { playUiSound } from '@/components/audio/sources/village';

/** Plays a UI sound. Safe before the audio engine exists. */
function uiSound(variant: 'click' | 'confirm' | 'back' | 'unlock' = 'click') {
  const engine = getSynthEngine();
  if (engine.ready) playUiSound(engine, variant);
}

/* ───────────────────────────────────────────────────────────────────────────
 * BUTTON
 * ─────────────────────────────────────────────────────────────────────────── */

const buttonVariants = cva(
  'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-sm font-medium transition-all duration-200 disabled:pointer-events-none disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-glow focus-visible:ring-offset-2 focus-visible:ring-offset-hollow-950 active:scale-[0.98]',
  {
    variants: {
      variant: {
        primary:
          'bg-gradient-to-b from-amber-glow to-amber-deep text-hollow-950 font-semibold shadow-lg shadow-amber-deep/25 hover:brightness-110 hover:shadow-amber-deep/40',
        secondary:
          'bg-hollow-800/80 text-hollow-100 border border-hollow-600/50 hover:bg-hollow-700/80 hover:border-hollow-500',
        ghost: 'text-hollow-300 hover:bg-hollow-800/60 hover:text-hollow-100',
        danger: 'bg-poppy/85 text-white hover:bg-poppy',
        outline:
          'border border-amber-glow/45 text-amber-soft hover:bg-amber-glow/10 hover:border-amber-glow/70',
      },
      size: {
        sm: 'h-8 px-3 text-xs',
        md: 'h-10 px-4',
        lg: 'h-12 px-6 text-base',
        icon: 'h-9 w-9',
      },
    },
    defaultVariants: { variant: 'secondary', size: 'md' },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
  /** Which UI sound to play on click. `null` for silence. */
  sound?: 'click' | 'confirm' | 'back' | null;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  { className, variant, size, asChild = false, sound = 'click', onClick, ...props },
  ref,
) {
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp
      ref={ref}
      className={cn(buttonVariants({ variant, size }), className)}
      onClick={(e: React.MouseEvent<HTMLButtonElement>) => {
        if (sound) uiSound(sound);
        onClick?.(e);
      }}
      {...props}
    />
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * SLIDER
 * ─────────────────────────────────────────────────────────────────────────── */

export interface SliderProps
  extends React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root> {
  label?: string;
  /** Formats the numeric value for display. */
  format?: (value: number) => string;
}

export const Slider = React.forwardRef<
  React.ComponentRef<typeof SliderPrimitive.Root>,
  SliderProps
>(function Slider({ className, label, format, value, defaultValue, ...props }, ref) {
  const displayValue = (value ?? defaultValue ?? [0])[0] ?? 0;

  return (
    <div className="w-full">
      {label && (
        <div className="mb-2 flex items-baseline justify-between gap-3">
          <label className="text-sm text-hollow-300">{label}</label>
          <span className="font-mono text-xs tabular-nums text-amber-soft">
            {format ? format(displayValue) : displayValue.toFixed(2)}
          </span>
        </div>
      )}
      <SliderPrimitive.Root
        ref={ref}
        value={value}
        defaultValue={defaultValue}
        className={cn(
          'relative flex w-full touch-none select-none items-center py-2',
          className,
        )}
        {...props}
      >
        <SliderPrimitive.Track className="relative h-1.5 w-full grow overflow-hidden rounded-full bg-hollow-700">
          <SliderPrimitive.Range className="absolute h-full rounded-full bg-gradient-to-r from-amber-deep to-amber-glow" />
        </SliderPrimitive.Track>
        <SliderPrimitive.Thumb
          className="block h-4 w-4 rounded-full border-2 border-amber-glow bg-hollow-950 shadow-md transition-transform hover:scale-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-glow focus-visible:ring-offset-2 focus-visible:ring-offset-hollow-900 active:scale-95"
          aria-label={label}
        />
      </SliderPrimitive.Root>
    </div>
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * SWITCH
 * ─────────────────────────────────────────────────────────────────────────── */

export interface SwitchProps
  extends React.ComponentPropsWithoutRef<typeof SwitchPrimitive.Root> {
  label?: string;
  description?: string;
}

export const Switch = React.forwardRef<
  React.ComponentRef<typeof SwitchPrimitive.Root>,
  SwitchProps
>(function Switch({ className, label, description, onCheckedChange, ...props }, ref) {
  const id = React.useId();
  return (
    <div className="flex items-start justify-between gap-4 py-1.5">
      {label && (
        <div className="min-w-0 flex-1">
          <label htmlFor={id} className="cursor-pointer text-sm text-hollow-200">
            {label}
          </label>
          {description && (
            <p className="mt-0.5 text-xs leading-relaxed text-hollow-400">{description}</p>
          )}
        </div>
      )}
      <SwitchPrimitive.Root
        id={id}
        ref={ref}
        onCheckedChange={(checked) => {
          uiSound(checked ? 'confirm' : 'back');
          onCheckedChange?.(checked);
        }}
        className={cn(
          'peer inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-glow focus-visible:ring-offset-2 focus-visible:ring-offset-hollow-900 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-amber-glow data-[state=unchecked]:bg-hollow-600',
          className,
        )}
        {...props}
      >
        <SwitchPrimitive.Thumb className="pointer-events-none block h-4 w-4 rounded-full bg-hollow-950 shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0" />
      </SwitchPrimitive.Root>
    </div>
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * TABS
 * ─────────────────────────────────────────────────────────────────────────── */

export const Tabs = TabsPrimitive.Root;

export const TabsList = React.forwardRef<
  React.ComponentRef<typeof TabsPrimitive.List>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.List>
>(function TabsList({ className, ...props }, ref) {
  return (
    <TabsPrimitive.List
      ref={ref}
      className={cn(
        'flex shrink-0 items-center gap-1 overflow-x-auto rounded-xl bg-hollow-900/60 p-1',
        className,
      )}
      {...props}
    />
  );
});

export const TabsTrigger = React.forwardRef<
  React.ComponentRef<typeof TabsPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Trigger>
>(function TabsTrigger({ className, onClick, ...props }, ref) {
  return (
    <TabsPrimitive.Trigger
      ref={ref}
      onClick={(e) => {
        uiSound('click');
        onClick?.(e);
      }}
      className={cn(
        'inline-flex shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg px-3 py-1.5 text-sm font-medium text-hollow-400 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-glow data-[state=active]:bg-hollow-700/80 data-[state=active]:text-amber-soft data-[state=active]:shadow-sm hover:text-hollow-200',
        className,
      )}
      {...props}
    />
  );
});

export const TabsContent = React.forwardRef<
  React.ComponentRef<typeof TabsPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TabsPrimitive.Content>
>(function TabsContent({ className, ...props }, ref) {
  return (
    <TabsPrimitive.Content
      ref={ref}
      className={cn(
        'mt-4 focus-visible:outline-none data-[state=active]:animate-fade-up',
        className,
      )}
      {...props}
    />
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * SELECT
 * ─────────────────────────────────────────────────────────────────────────── */

export const Select = SelectPrimitive.Root;
export const SelectValue = SelectPrimitive.Value;

export const SelectTrigger = React.forwardRef<
  React.ComponentRef<typeof SelectPrimitive.Trigger>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Trigger>
>(function SelectTrigger({ className, children, ...props }, ref) {
  return (
    <SelectPrimitive.Trigger
      ref={ref}
      className={cn(
        'flex h-9 w-full items-center justify-between gap-2 rounded-lg border border-hollow-600/60 bg-hollow-800/70 px-3 py-1.5 text-sm text-hollow-100 transition-colors hover:border-hollow-500 focus:outline-none focus:ring-2 focus:ring-amber-glow disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      {...props}
    >
      {children}
      <SelectPrimitive.Icon asChild>
        <ChevronDown className="h-4 w-4 shrink-0 opacity-60" />
      </SelectPrimitive.Icon>
    </SelectPrimitive.Trigger>
  );
});

export const SelectContent = React.forwardRef<
  React.ComponentRef<typeof SelectPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Content>
>(function SelectContent({ className, children, position = 'popper', ...props }, ref) {
  return (
    <SelectPrimitive.Portal>
      <SelectPrimitive.Content
        ref={ref}
        position={position}
        className={cn(
          'glass relative z-[200] max-h-72 min-w-[8rem] overflow-hidden rounded-xl shadow-xl',
          position === 'popper' && 'translate-y-1',
          className,
        )}
        {...props}
      >
        <SelectPrimitive.Viewport className="p-1">{children}</SelectPrimitive.Viewport>
      </SelectPrimitive.Content>
    </SelectPrimitive.Portal>
  );
});

export const SelectItem = React.forwardRef<
  React.ComponentRef<typeof SelectPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof SelectPrimitive.Item>
>(function SelectItem({ className, children, ...props }, ref) {
  return (
    <SelectPrimitive.Item
      ref={ref}
      className={cn(
        'relative flex w-full cursor-pointer select-none items-center rounded-lg py-1.5 pl-8 pr-2 text-sm text-hollow-200 outline-none transition-colors focus:bg-hollow-700/70 focus:text-amber-soft data-[disabled]:pointer-events-none data-[disabled]:opacity-50',
        className,
      )}
      {...props}
    >
      <span className="absolute left-2 flex h-3.5 w-3.5 items-center justify-center">
        <SelectPrimitive.ItemIndicator>
          <Check className="h-3.5 w-3.5 text-amber-glow" />
        </SelectPrimitive.ItemIndicator>
      </span>
      <SelectPrimitive.ItemText>{children}</SelectPrimitive.ItemText>
    </SelectPrimitive.Item>
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * DIALOG
 * ─────────────────────────────────────────────────────────────────────────── */

export const Dialog = DialogPrimitive.Root;
export const DialogTrigger = DialogPrimitive.Trigger;
export const DialogClose = DialogPrimitive.Close;
export const DialogTitle = DialogPrimitive.Title;
export const DialogDescription = DialogPrimitive.Description;

export const DialogContent = React.forwardRef<
  React.ComponentRef<typeof DialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DialogPrimitive.Content>
>(function DialogContent({ className, children, ...props }, ref) {
  return (
    <DialogPrimitive.Portal>
      <DialogPrimitive.Overlay className="fixed inset-0 z-[150] bg-black/65 backdrop-blur-sm data-[state=open]:animate-in data-[state=open]:fade-in" />
      <DialogPrimitive.Content
        ref={ref}
        className={cn(
          'glass fixed left-1/2 top-1/2 z-[151] w-[min(94vw,34rem)] -translate-x-1/2 -translate-y-1/2 rounded-panel p-6 shadow-2xl focus:outline-none',
          className,
        )}
        {...props}
      >
        {children}
      </DialogPrimitive.Content>
    </DialogPrimitive.Portal>
  );
});

/* ───────────────────────────────────────────────────────────────────────────
 * MISC
 * ─────────────────────────────────────────────────────────────────────────── */

export const ScrollArea = React.forwardRef<
  React.ComponentRef<typeof ScrollAreaPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ScrollAreaPrimitive.Root>
>(function ScrollArea({ className, children, ...props }, ref) {
  return (
    <ScrollAreaPrimitive.Root
      ref={ref}
      className={cn('relative overflow-hidden', className)}
      {...props}
    >
      <ScrollAreaPrimitive.Viewport className="h-full w-full rounded-[inherit] [&>div]:!block">
        {children}
      </ScrollAreaPrimitive.Viewport>
      <ScrollAreaPrimitive.Scrollbar
        orientation="vertical"
        className="flex w-2 touch-none select-none p-0.5 transition-colors"
      >
        <ScrollAreaPrimitive.Thumb className="relative flex-1 rounded-full bg-hollow-500/60" />
      </ScrollAreaPrimitive.Scrollbar>
      <ScrollAreaPrimitive.Corner />
    </ScrollAreaPrimitive.Root>
  );
});

export const Separator = React.forwardRef<
  React.ComponentRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(function Separator({ className, orientation = 'horizontal', decorative = true, ...props }, ref) {
  return (
    <SeparatorPrimitive.Root
      ref={ref}
      decorative={decorative}
      orientation={orientation}
      className={cn(
        'shrink-0 bg-hollow-600/40',
        orientation === 'horizontal' ? 'h-px w-full' : 'h-full w-px',
        className,
      )}
      {...props}
    />
  );
});

export const TooltipProvider = TooltipPrimitive.Provider;
export const Tooltip = TooltipPrimitive.Root;
export const TooltipTrigger = TooltipPrimitive.Trigger;

export const TooltipContent = React.forwardRef<
  React.ComponentRef<typeof TooltipPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof TooltipPrimitive.Content>
>(function TooltipContent({ className, sideOffset = 6, ...props }, ref) {
  return (
    <TooltipPrimitive.Portal>
      <TooltipPrimitive.Content
        ref={ref}
        sideOffset={sideOffset}
        className={cn(
          'glass z-[300] max-w-xs rounded-lg px-2.5 py-1.5 text-xs text-hollow-200 shadow-lg',
          className,
        )}
        {...props}
      />
    </TooltipPrimitive.Portal>
  );
});

/** A labelled group of settings. */
export function SettingsGroup({
  title,
  description,
  children,
}: {
  title: string;
  description?: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-6">
      <h3 className="mb-1 font-display text-sm uppercase tracking-widest text-amber-soft/70">
        {title}
      </h3>
      {description && <p className="mb-3 text-xs text-hollow-400">{description}</p>}
      <div className="space-y-3 rounded-xl bg-hollow-900/40 p-3.5">{children}</div>
    </section>
  );
}

/** A row of mutually-exclusive choice chips. */
export function ChipGroup<T extends string>({
  options,
  value,
  onChange,
  label,
}: {
  options: ReadonlyArray<{ id: T; label: string; icon?: string }>;
  value: T;
  onChange: (value: T) => void;
  label?: string;
}) {
  return (
    <div>
      {label && <div className="mb-2 text-sm text-hollow-300">{label}</div>}
      <div className="flex flex-wrap gap-1.5">
        {options.map((option) => (
          <button
            key={option.id}
            type="button"
            onClick={() => {
              uiSound('click');
              onChange(option.id);
            }}
            className={cn(
              'rounded-lg border px-2.5 py-1.5 text-xs font-medium transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-glow',
              value === option.id
                ? 'border-amber-glow/70 bg-amber-glow/15 text-amber-soft'
                : 'border-hollow-600/50 bg-hollow-800/50 text-hollow-300 hover:border-hollow-500 hover:text-hollow-100',
            )}
            aria-pressed={value === option.id}
          >
            {option.icon && <span className="mr-1">{option.icon}</span>}
            {option.label}
          </button>
        ))}
      </div>
    </div>
  );
}
